version: '3'
services:
    # db:
    #     image: postgres:11
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #     volumes:
    #         - ./tmp/db:/var/lib/postgresql/data
    ret:
        image: reticulum:demo
        environment:
            - "DB_HOST=10.30.176.65"
        command: bash -c "source ~/.bashrc; popd; mix deps.get; mix ecto.create; mix ecto.migrate; mix phx.server"
        volumes:
            - .:/ret
        ports:
            - "4000:4000"
        # depends_on:
        #     - db
